
package TUNAME;
import Metodos.saveImage;
import Metodos.openImage;
import TUNAME.*;
import CLASES.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */




/**
 *
 * @author Familia
 */
public class Vehiculos extends javax.swing.JFrame {

    /**
     * Creates new form si
     */
    controladorVehiculos contVeh = new controladorVehiculos();
    public Vehiculos() {
        initComponents();
        updateTablaVehiculos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JAgragar_Documentacion = new javax.swing.JDialog();
        Agregar_Documentacion = new javax.swing.JPanel();
        PanelSaludo1 = new javax.swing.JPanel();
        lblTextoMorado1 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        btnContrato = new javax.swing.JLabel();
        btnFactura = new javax.swing.JLabel();
        btnTenencia = new javax.swing.JLabel();
        btnMantenimiento = new javax.swing.JLabel();
        btnTarjeta = new javax.swing.JLabel();
        btnID = new javax.swing.JLabel();
        JConsulta_Documentacion = new javax.swing.JDialog();
        Agregar_Documentacion1 = new javax.swing.JPanel();
        PanelSaludo2 = new javax.swing.JPanel();
        lblTextoMorado2 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        btnContrato_C = new javax.swing.JLabel();
        btnFactura_C = new javax.swing.JLabel();
        btnTenencia_C = new javax.swing.JLabel();
        btnRegistro_C = new javax.swing.JLabel();
        btnCirculacion_C = new javax.swing.JLabel();
        btnIdentificacion_C = new javax.swing.JLabel();
        JVentas = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        PanelSaludo3 = new javax.swing.JPanel();
        lblTextoMorado3 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lblNombreA2 = new javax.swing.JLabel();
        lblNombreA3 = new javax.swing.JLabel();
        lblNombreA5 = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblCLN = new javax.swing.JLabel();
        lblIngresos = new javax.swing.JLabel();
        lblNombreA4 = new javax.swing.JLabel();
        lblNombreA6 = new javax.swing.JLabel();
        lblNombreA = new javax.swing.JLabel();
        lblNombreA7 = new javax.swing.JLabel();
        lblPromedio1 = new javax.swing.JLabel();
        lblNombreA8 = new javax.swing.JLabel();
        btnVentaA = new javax.swing.JLabel();
        btnCancelarV = new javax.swing.JLabel();
        JRegistroCliente = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApaterno = new javax.swing.JTextField();
        txtAmaterno = new javax.swing.JTextField();
        txtCorreoE = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRFC = new javax.swing.JTextField();
        PanelSaludo4 = new javax.swing.JPanel();
        lblTextoMorado4 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaClientes1 = new javax.swing.JTable();
        btnCliente_A = new javax.swing.JLabel();
        btnEditarCliente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PanelSaludo = new javax.swing.JPanel();
        lblSaludito = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        PanelLateral = new javax.swing.JPanel();
        PLautos = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        PLusuario = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        PLsalir = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        PLTenencias = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PNVentanas = new javax.swing.JTabbedPane();
        PLVehiculos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVenta = new javax.swing.JLabel();
        btnDocumentacionC = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        btnDocumentacion = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        pnCrudVehiculos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtVariante = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cboGasolina = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cboDescuento = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        cboTenencia = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaVehiculos = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        cboFecha = new TUNAME.panelCalendario();
        PLTenencias_2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaTenencias = new javax.swing.JTable();
        btnTenencia_P = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        JAgragar_Documentacion.setResizable(false);
        JAgragar_Documentacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar_Documentacion.setBackground(new java.awt.Color(255, 255, 255));
        Agregar_Documentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSaludo1.setBackground(new java.awt.Color(75, 75, 75));
        PanelSaludo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMorado1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTextoMorado1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMorado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMorado1.setText("Documentación");
        lblTextoMorado1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo1.add(lblTextoMorado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 390, 40));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("MSK SEMINUEVOS");
        jLabel59.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, 40));

        Agregar_Documentacion.add(PanelSaludo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 100));

        btnContrato.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnContrato.setForeground(new java.awt.Color(25, 25, 25));
        btnContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/contract.png"))); // NOI18N
        btnContrato.setText(" Contrato de compra");
        btnContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContratoMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 60));

        btnFactura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFactura.setForeground(new java.awt.Color(25, 25, 25));
        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/bill.png"))); // NOI18N
        btnFactura.setText(" Factura original");
        btnFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturaMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 60));

        btnTenencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTenencia.setForeground(new java.awt.Color(25, 25, 25));
        btnTenencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/document.png"))); // NOI18N
        btnTenencia.setText(" Comprobante de tenencia");
        btnTenencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTenencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTenenciaMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnTenencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 280, 60));

        btnMantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMantenimiento.setForeground(new java.awt.Color(25, 25, 25));
        btnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/predictive.png"))); // NOI18N
        btnMantenimiento.setText(" Registro de mantenimiento");
        btnMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMantenimientoMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 330, 60));

        btnTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTarjeta.setForeground(new java.awt.Color(25, 25, 25));
        btnTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/credit-card.png"))); // NOI18N
        btnTarjeta.setText(" Tarjeta de circulacion");
        btnTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTarjetaMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, 60));

        btnID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnID.setForeground(new java.awt.Color(25, 25, 25));
        btnID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/card.png"))); // NOI18N
        btnID.setText(" Identificacion del ultimo dueño");
        btnID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIDMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 60));

        JAgragar_Documentacion.getContentPane().add(Agregar_Documentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 560));

        JConsulta_Documentacion.setResizable(false);
        JConsulta_Documentacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar_Documentacion1.setBackground(new java.awt.Color(255, 255, 255));
        Agregar_Documentacion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSaludo2.setBackground(new java.awt.Color(75, 75, 75));
        PanelSaludo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMorado2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTextoMorado2.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMorado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMorado2.setText("Consulta de Documentación");
        lblTextoMorado2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo2.add(lblTextoMorado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 40));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("MSK SEMINUEVOS");
        jLabel60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, 40));

        Agregar_Documentacion1.add(PanelSaludo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        btnContrato_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnContrato_C.setForeground(new java.awt.Color(25, 25, 25));
        btnContrato_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/contract.png"))); // NOI18N
        btnContrato_C.setText(" Contrato de compra");
        btnContrato_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContrato_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContrato_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnContrato_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 60));

        btnFactura_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFactura_C.setForeground(new java.awt.Color(25, 25, 25));
        btnFactura_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/bill.png"))); // NOI18N
        btnFactura_C.setText(" Factura original");
        btnFactura_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFactura_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFactura_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnFactura_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 60));

        btnTenencia_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTenencia_C.setForeground(new java.awt.Color(25, 25, 25));
        btnTenencia_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/document.png"))); // NOI18N
        btnTenencia_C.setText(" Comprobante de tenencia");
        btnTenencia_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTenencia_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTenencia_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnTenencia_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 280, 60));

        btnRegistro_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistro_C.setForeground(new java.awt.Color(25, 25, 25));
        btnRegistro_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/predictive.png"))); // NOI18N
        btnRegistro_C.setText(" Registro de mantenimiento");
        btnRegistro_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistro_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnRegistro_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 330, 60));

        btnCirculacion_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCirculacion_C.setForeground(new java.awt.Color(25, 25, 25));
        btnCirculacion_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/credit-card.png"))); // NOI18N
        btnCirculacion_C.setText(" Tarjeta de circulacion");
        btnCirculacion_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCirculacion_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCirculacion_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnCirculacion_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, 60));

        btnIdentificacion_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIdentificacion_C.setForeground(new java.awt.Color(25, 25, 25));
        btnIdentificacion_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/card.png"))); // NOI18N
        btnIdentificacion_C.setText(" Identificacion del ultimo dueño");
        btnIdentificacion_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIdentificacion_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIdentificacion_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnIdentificacion_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 60));

        JConsulta_Documentacion.getContentPane().add(Agregar_Documentacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 560));

        JVentas.setResizable(false);
        JVentas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSaludo3.setBackground(new java.awt.Color(75, 75, 75));
        PanelSaludo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMorado3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTextoMorado3.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMorado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMorado3.setText("Ventas");
        lblTextoMorado3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo3.add(lblTextoMorado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1020, 40));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("MSK SEMINUEVOS");
        jLabel61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1020, 40));

        jPanel3.add(PanelSaludo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 100));

        lblNombreA2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA2.setForeground(new java.awt.Color(25, 25, 25));
        lblNombreA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/price-tag.png"))); // NOI18N
        lblNombreA2.setText(" Precio de Compra");
        jPanel3.add(lblNombreA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 250, -1));

        lblNombreA3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA3.setForeground(new java.awt.Color(25, 25, 25));
        lblNombreA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/pricing.png"))); // NOI18N
        lblNombreA3.setText(" Precio de Venta");
        jPanel3.add(lblNombreA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 250, -1));

        lblNombreA5.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA5.setForeground(new java.awt.Color(25, 25, 25));
        lblNombreA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/calendar.png"))); // NOI18N
        lblNombreA5.setText(" Años transcurridos");
        jPanel3.add(lblNombreA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 240, -1));

        lblPromedio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPromedio.setForeground(new java.awt.Color(54, 33, 89));
        lblPromedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromedio.setText("jLabel2");
        jPanel3.add(lblPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 100, -1));

        lblCLN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCLN.setForeground(new java.awt.Color(54, 33, 89));
        lblCLN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCLN.setText("jLabel2");
        jPanel3.add(lblCLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 100, -1));

        lblIngresos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIngresos.setForeground(new java.awt.Color(54, 33, 89));
        lblIngresos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngresos.setText("jLabel2");
        jPanel3.add(lblIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 100, -1));

        lblNombreA4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA4.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreA4.setText("______________");
        jPanel3.add(lblNombreA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 120, -1));

        lblNombreA6.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA6.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreA6.setText("______________");
        jPanel3.add(lblNombreA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 120, -1));

        lblNombreA.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreA.setText("______________");
        jPanel3.add(lblNombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 120, -1));

        lblNombreA7.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA7.setForeground(new java.awt.Color(25, 25, 25));
        lblNombreA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/taxes.png"))); // NOI18N
        lblNombreA7.setText(" Impuestos agregados");
        jPanel3.add(lblNombreA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 250, -1));

        lblPromedio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPromedio1.setForeground(new java.awt.Color(54, 33, 89));
        lblPromedio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromedio1.setText("jLabel2");
        jPanel3.add(lblPromedio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 100, -1));

        lblNombreA8.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblNombreA8.setForeground(new java.awt.Color(54, 33, 89));
        lblNombreA8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreA8.setText("______________");
        jPanel3.add(lblNombreA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 120, -1));

        btnVentaA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVentaA.setForeground(new java.awt.Color(25, 25, 25));
        btnVentaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/new-car.png"))); // NOI18N
        btnVentaA.setText(" Vender");
        btnVentaA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnVentaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 110, 60));

        btnCancelarV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarV.setForeground(new java.awt.Color(25, 25, 25));
        btnCancelarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/paper.png"))); // NOI18N
        btnCancelarV.setText("Cancelar");
        btnCancelarV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarVMouseClicked(evt);
            }
        });
        jPanel3.add(btnCancelarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 120, 60));

        JVentas.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 6, 1020, 430));

        JRegistroCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/human-capital_1.png"))); // NOI18N

        jLabel43.setBackground(new java.awt.Color(25, 25, 25));
        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(25, 25, 25));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Clientes");

        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Nombre(s)");
        txtNombre.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtNombre.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApaterno.setForeground(new java.awt.Color(153, 153, 153));
        txtApaterno.setText("Apellido Paterno");
        txtApaterno.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtApaterno.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtApaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApaternoMouseClicked(evt);
            }
        });
        txtApaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApaternoActionPerformed(evt);
            }
        });
        txtApaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApaternoKeyTyped(evt);
            }
        });

        txtAmaterno.setForeground(new java.awt.Color(153, 153, 153));
        txtAmaterno.setText("Apellido Materno");
        txtAmaterno.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtAmaterno.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtAmaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAmaternoMouseClicked(evt);
            }
        });
        txtAmaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmaternoActionPerformed(evt);
            }
        });
        txtAmaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmaternoKeyTyped(evt);
            }
        });

        txtCorreoE.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoE.setText("Correo Electronico");
        txtCorreoE.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtCorreoE.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtCorreoE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoEMouseClicked(evt);
            }
        });
        txtCorreoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoEActionPerformed(evt);
            }
        });
        txtCorreoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoEKeyTyped(evt);
            }
        });

        txtTelefono.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefono.setText("Telefono");
        txtTelefono.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtTelefono.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseClicked(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtRFC.setForeground(new java.awt.Color(153, 153, 153));
        txtRFC.setText("RFC");
        txtRFC.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtRFC.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtRFC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRFCMouseClicked(evt);
            }
        });
        txtRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRFCActionPerformed(evt);
            }
        });
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtApaterno)
                    .addComponent(txtAmaterno)
                    .addComponent(txtCorreoE)
                    .addComponent(txtTelefono)
                    .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 250, 420));

        PanelSaludo4.setBackground(new java.awt.Color(75, 75, 75));
        PanelSaludo4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMorado4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTextoMorado4.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMorado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMorado4.setText("Clientes");
        lblTextoMorado4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo4.add(lblTextoMorado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1250, 40));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("MSK SEMINUEVOS");
        jLabel62.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo4.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1250, 40));

        jPanel4.add(PanelSaludo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 100));

        jScrollPane6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TablaClientes1.setAutoCreateRowSorter(true);
        TablaClientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Gmail", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaClientes1.setGridColor(new java.awt.Color(255, 255, 255));
        TablaClientes1.setSelectionBackground(new java.awt.Color(75, 75, 75));
        TablaClientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClientes1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TablaClientes1);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 860, 210));

        btnCliente_A.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCliente_A.setForeground(new java.awt.Color(25, 25, 25));
        btnCliente_A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/add-user.png"))); // NOI18N
        btnCliente_A.setText("  Agregar Cliente");
        btnCliente_A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(btnCliente_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 200, 60));

        btnEditarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(25, 25, 25));
        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/edit.png"))); // NOI18N
        btnEditarCliente.setText(" Editar Cliente");
        btnEditarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(btnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 170, 60));

        JRegistroCliente.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1250, 560));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1800, 750));
        setPreferredSize(new java.awt.Dimension(1800, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSaludo.setBackground(new java.awt.Color(75, 75, 75));
        PanelSaludo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSaludito.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSaludito.setForeground(new java.awt.Color(255, 255, 255));
        lblSaludito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaludito.setText("¡Bienvenido de Vuelta!");
        lblSaludito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo.add(lblSaludito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1290, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("MSK SEMINUEVOS");
        jLabel58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1290, 40));

        jPanel1.add(PanelSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 1520, 100));

        PanelLateral.setBackground(new java.awt.Color(25, 25, 25));
        PanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PLautos.setBackground(new java.awt.Color(40, 40, 40));
        PLautos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLautosMouseMoved(evt);
            }
        });
        PLautos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLautosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLautosMouseExited(evt);
            }
        });
        PLautos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/car (1).png"))); // NOI18N
        PLautos.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Vehiculos");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PLautos.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 0, 116, 60));

        PanelLateral.add(PLautos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 310, 60));

        PLusuario.setBackground(new java.awt.Color(40, 40, 40));
        PLusuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLusuarioMouseMoved(evt);
            }
        });
        PLusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLusuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLusuarioMouseExited(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cambiar.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cambiar de usuario");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PLusuarioLayout = new javax.swing.GroupLayout(PLusuario);
        PLusuario.setLayout(PLusuarioLayout);
        PLusuarioLayout.setHorizontalGroup(
            PLusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLusuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PLusuarioLayout.setVerticalGroup(
            PLusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLusuarioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PLusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PanelLateral.add(PLusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 280, 50));

        PLsalir.setBackground(new java.awt.Color(40, 40, 40));
        PLsalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLsalirMouseMoved(evt);
            }
        });
        PLsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLsalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLsalirMouseExited(evt);
            }
        });
        PLsalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cerrar-sesion.png"))); // NOI18N
        PLsalir.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Salir");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PLsalir.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 6, 119, 34));

        PanelLateral.add(PLsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 290, 50));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Administrador");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelLateral.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("_____________________");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelLateral.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 40));

        PLTenencias.setBackground(new java.awt.Color(40, 40, 40));
        PLTenencias.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLTenenciasMouseMoved(evt);
            }
        });
        PLTenencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLTenenciasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLTenenciasMouseExited(evt);
            }
        });
        PLTenencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/atm.png"))); // NOI18N
        PLTenencias.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 40, 60));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Tenencias");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PLTenencias.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 116, 20));

        PanelLateral.add(PLTenencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 310, 60));

        jPanel1.add(PanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 750));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hecho con ♥");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1300, 50));

        PLVehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(25, 25, 25));
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/new-car.png"))); // NOI18N
        btnVenta.setText(" Vender");
        btnVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentaMouseClicked(evt);
            }
        });
        jPanel2.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 120, 60));

        btnDocumentacionC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDocumentacionC.setForeground(new java.awt.Color(25, 25, 25));
        btnDocumentacionC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/search.png"))); // NOI18N
        btnDocumentacionC.setText("  Consultar Documentacion");
        btnDocumentacionC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocumentacionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocumentacionCMouseClicked(evt);
            }
        });
        jPanel2.add(btnDocumentacionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, 270, 60));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(25, 25, 25));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/rental-car.png"))); // NOI18N
        btnAgregar.setText("  Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 130, 60));

        btnDocumentacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDocumentacion.setForeground(new java.awt.Color(25, 25, 25));
        btnDocumentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/checklist.png"))); // NOI18N
        btnDocumentacion.setText("  Agregar Documentacion");
        btnDocumentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocumentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocumentacionMouseClicked(evt);
            }
        });
        jPanel2.add(btnDocumentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 270, 60));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(25, 25, 25));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/mechanical.png"))); // NOI18N
        btnEditar.setText(" Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 100, 60));

        pnCrudVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        pnCrudVehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/car-wash.png"))); // NOI18N
        pnCrudVehiculos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 6, 70, -1));

        jLabel42.setBackground(new java.awt.Color(25, 25, 25));
        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(25, 25, 25));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Vehiculos");
        pnCrudVehiculos.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 240, 30));

        txtModelo.setForeground(new java.awt.Color(153, 153, 153));
        txtModelo.setText("Modelo");
        txtModelo.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtModelo.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtModeloMouseClicked(evt);
            }
        });
        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModeloKeyTyped(evt);
            }
        });
        pnCrudVehiculos.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 240, 30));

        txtVariante.setForeground(new java.awt.Color(153, 153, 153));
        txtVariante.setText("Variante");
        txtVariante.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtVariante.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtVariante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVarianteMouseClicked(evt);
            }
        });
        txtVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVarianteActionPerformed(evt);
            }
        });
        txtVariante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVarianteKeyTyped(evt);
            }
        });
        pnCrudVehiculos.add(txtVariante, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 30));

        txtAnio.setForeground(new java.awt.Color(153, 153, 153));
        txtAnio.setText("Año");
        txtAnio.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtAnio.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnioMouseClicked(evt);
            }
        });
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioKeyTyped(evt);
            }
        });
        pnCrudVehiculos.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 202, 240, 30));

        txtColor.setForeground(new java.awt.Color(153, 153, 153));
        txtColor.setText("Kilometraje");
        txtColor.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtColor.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtColorMouseClicked(evt);
            }
        });
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });
        pnCrudVehiculos.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 244, 240, 30));

        txtKilometraje.setForeground(new java.awt.Color(153, 153, 153));
        txtKilometraje.setText("Precio de Compra");
        txtKilometraje.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtKilometraje.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtKilometraje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKilometrajeMouseClicked(evt);
            }
        });
        txtKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilometrajeActionPerformed(evt);
            }
        });
        txtKilometraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKilometrajeKeyTyped(evt);
            }
        });
        pnCrudVehiculos.add(txtKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 286, 240, 30));

        txtPrecio.setForeground(new java.awt.Color(153, 153, 153));
        txtPrecio.setText("Precio de Venta");
        txtPrecio.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtPrecio.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrecioMouseClicked(evt);
            }
        });
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        pnCrudVehiculos.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 328, 240, 30));

        cboGasolina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Premium", "Diésel", "Etanol (E85)", "Electrico" }));
        cboGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGasolinaActionPerformed(evt);
            }
        });
        pnCrudVehiculos.add(cboGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jLabel36.setText("Tipo de Gasolina");
        pnCrudVehiculos.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 93, 25));

        jLabel37.setText("Descuento");
        pnCrudVehiculos.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 81, 25));

        cboDescuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "25%", "50%", "75%" }));
        cboDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDescuentoActionPerformed(evt);
            }
        });
        pnCrudVehiculos.add(cboDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 96, -1));

        jLabel38.setText("Tenencia");
        pnCrudVehiculos.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 99, 25));

        cboTenencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagada", "Adeudo" }));
        cboTenencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenenciaActionPerformed(evt);
            }
        });
        pnCrudVehiculos.add(cboTenencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 96, -1));

        jPanel2.add(pnCrudVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 480));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TablaVehiculos.setAutoCreateRowSorter(true);
        TablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Modelo", "Variante", "Año", "Precio", "Kilometraje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaVehiculos.setGridColor(new java.awt.Color(255, 255, 255));
        TablaVehiculos.setSelectionBackground(new java.awt.Color(75, 75, 75));
        TablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaVehiculos);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 49, 870, 240));

        jLabel45.setBackground(new java.awt.Color(25, 25, 25));
        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(25, 25, 25));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/calendar.png"))); // NOI18N
        jLabel45.setText(" Fecha de Compra");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 180, 40));
        jPanel2.add(cboFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        PLVehiculos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 590));

        PNVentanas.addTab("tab1", PLVehiculos);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TablaTenencias.setAutoCreateRowSorter(true);
        TablaTenencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Modelo", "Tenencia Vencida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaTenencias.setGridColor(new java.awt.Color(255, 255, 255));
        TablaTenencias.setSelectionBackground(new java.awt.Color(75, 75, 75));
        TablaTenencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaTenenciasMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(TablaTenencias);

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 928, 197));

        btnTenencia_P.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTenencia_P.setForeground(new java.awt.Color(25, 25, 25));
        btnTenencia_P.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTenencia_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/file.png"))); // NOI18N
        btnTenencia_P.setText("  Tenencia Pagada");
        btnTenencia_P.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(btnTenencia_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 350, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/logo.jpg"))); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 400, -1, 180));

        javax.swing.GroupLayout PLTenencias_2Layout = new javax.swing.GroupLayout(PLTenencias_2);
        PLTenencias_2.setLayout(PLTenencias_2Layout);
        PLTenencias_2Layout.setHorizontalGroup(
            PLTenencias_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PLTenencias_2Layout.setVerticalGroup(
            PLTenencias_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLTenencias_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PNVentanas.addTab("tab2", PLTenencias_2);

        jPanel1.add(PNVentanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 1300, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLusuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLusuarioMouseMoved
        // TODO add your handling code here:
        PLusuario.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_PLusuarioMouseMoved

    private void PLusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLusuarioMouseClicked
            this.dispose();
            LOGIN_1 log = new LOGIN_1();
            log.setVisible(true);
    }//GEN-LAST:event_PLusuarioMouseClicked

    private void PLusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLusuarioMouseExited
        // TODO add your handling code here:
     PLusuario.setBackground(new Color(40,40,40));   
    }//GEN-LAST:event_PLusuarioMouseExited

    private void PLsalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLsalirMouseMoved
        // TODO add your handling code here:
        PLsalir.setBackground(new Color(60,60,60));
        
    }//GEN-LAST:event_PLsalirMouseMoved

    private void PLsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLsalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_PLsalirMouseClicked

    private void PLsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLsalirMouseExited
        // TODO add your handling code here:
        PLsalir.setBackground(new Color(40,40,40));
    }//GEN-LAST:event_PLsalirMouseExited

    private void PLautosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLautosMouseExited
        // TODO add your handling code here:
        PLautos.setBackground(new Color(40,40,40));
    }//GEN-LAST:event_PLautosMouseExited

    private void PLautosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLautosMouseClicked
        PNVentanas.setSelectedIndex(0);
        lblSaludito.setText("Vehiculos");
    }//GEN-LAST:event_PLautosMouseClicked

    private void PLautosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLautosMouseMoved
        // TODO add your handling code here:
        PLautos.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_PLautosMouseMoved
    private int selectedRow_TVehiculos(){
        return Integer.parseInt(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 0).toString());
    }
    private void btnFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMouseClicked
        //tablaVentas.getValueAt(tablaVentas.getSelectedRow(),0).toString()
        new saveImage().selectImage("Factura",1); // Añadir getIDCarro()
        System.out.println(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_btnFacturaMouseClicked

    private void btnTenenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTenenciaMouseClicked
        new saveImage().selectImage("Tenencia", 1); // Añadir getIDCarro()
    }//GEN-LAST:event_btnTenenciaMouseClicked

    private void btnTarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarjetaMouseClicked
        new saveImage().selectImage("Tarjeta", 1); // Añadir getIDCarro()
    }//GEN-LAST:event_btnTarjetaMouseClicked

    private void btnContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratoMouseClicked
        new saveImage().selectImage("Contrato", 1); // Añadir getIDCarro()
    }//GEN-LAST:event_btnContratoMouseClicked

    private void btnIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIDMouseClicked
        new saveImage().selectImage("ID", 1); // Añadir getIDCarro()
    }//GEN-LAST:event_btnIDMouseClicked

    private void btnMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoMouseClicked
        new saveImage().selectImage("Mantenimiento", 1); // Añadir getIDCarro()
    }//GEN-LAST:event_btnMantenimientoMouseClicked

    private void btnTenencia_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTenencia_CMouseClicked
        try {
            new openImage().buscar("Tenencia", 1);            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnTenencia_CMouseClicked

    private void btnCirculacion_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculacion_CMouseClicked
        try {
            new openImage().buscar("Tarjeta", 1);            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCirculacion_CMouseClicked

    private void btnContrato_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContrato_CMouseClicked
        try {
            new openImage().buscar("Contrato", 1);            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnContrato_CMouseClicked

    private void btnIdentificacion_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdentificacion_CMouseClicked
        try {
            new openImage().buscar("ID", 1);            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnIdentificacion_CMouseClicked

    private void btnRegistro_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistro_CMouseClicked
        try {
            new openImage().buscar("Mantenimiento", 1);            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRegistro_CMouseClicked

    private void btnFactura_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFactura_CMouseClicked
        try {
            new openImage().buscar("Factura", 1);            
        } catch (Exception e) {
        }    }//GEN-LAST:event_btnFactura_CMouseClicked

    private void PLTenenciasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLTenenciasMouseMoved
        PLTenencias.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_PLTenenciasMouseMoved

    private void PLTenenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLTenenciasMouseClicked
        PNVentanas.setSelectedIndex(1);
        lblSaludito.setText("Tenencias Vencidas");
        updateTablaTenencias();
    }//GEN-LAST:event_PLTenenciasMouseClicked

    private void PLTenenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLTenenciasMouseExited
        PLTenencias.setBackground(new Color(40,40,40));
    }//GEN-LAST:event_PLTenenciasMouseExited

    private void btnVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaMouseClicked
        JVentas.setSize(1019, 436);
        JVentas.setLocationRelativeTo(null);

        JVentas.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnVentaMouseClicked

    private void btnDocumentacionCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentacionCMouseClicked
        JConsulta_Documentacion.setSize(440,590);
        JConsulta_Documentacion.setLocationRelativeTo(null);
        JConsulta_Documentacion.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnDocumentacionCMouseClicked

    private void btnDocumentacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentacionMouseClicked
        JAgragar_Documentacion.setSize(390,590);
        JAgragar_Documentacion.setLocationRelativeTo(null);

        JAgragar_Documentacion.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnDocumentacionMouseClicked

    private void txtModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModeloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloMouseClicked

    private void txtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyTyped
        // TODO add your handling code here:}
        char c = evt.getKeyChar();

        if(Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtModeloKeyTyped

    private void txtVarianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVarianteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarianteMouseClicked

    private void txtVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVarianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarianteActionPerformed

    private void txtVarianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVarianteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarianteKeyTyped

    private void txtAnioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioMouseClicked

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioKeyTyped

    private void txtColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtColorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorMouseClicked

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorKeyTyped

    private void txtKilometrajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKilometrajeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrajeMouseClicked

    private void txtKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrajeActionPerformed

    private void txtKilometrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKilometrajeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrajeKeyTyped

    private void txtPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioMouseClicked

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void cboGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGasolinaActionPerformed

    private void cboDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDescuentoActionPerformed

    private void TablaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVehiculosMouseClicked

    }//GEN-LAST:event_TablaVehiculosMouseClicked

    private void TablaTenenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaTenenciasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaTenenciasMouseClicked

    private void cboTenenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenenciaActionPerformed

    private void TablaClientes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClientes1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaClientes1MouseClicked

    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCKeyTyped

    private void txtRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCActionPerformed

    private void txtRFCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRFCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCMouseClicked

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoMouseClicked

    private void txtCorreoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoEKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEKeyTyped

    private void txtCorreoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEActionPerformed

    private void txtCorreoEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEMouseClicked

    private void txtAmaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmaternoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmaternoKeyTyped

    private void txtAmaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmaternoActionPerformed

    private void txtAmaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAmaternoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmaternoMouseClicked

    private void txtApaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApaternoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApaternoKeyTyped

    private void txtApaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApaternoActionPerformed

    private void txtApaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApaternoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApaternoMouseClicked

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMouseClicked

    private void btnCancelarVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarVMouseClicked
       JVentas.dispose();
    }//GEN-LAST:event_btnCancelarVMouseClicked
    
    private void updateTablaVehiculos(){
        contVeh.ActualizarVehiculos();
        DefaultTableModel modelo = new DefaultTableModel();
        
        String [] cabecera = {"ID Vehiculo","Modelo","Variante","Año","Precio de compra","Kilometraje","Tipo de Gasolina","Precio de venta"};
        
        for (String i : cabecera)
            modelo.addColumn(i);
        
        TablaVehiculos.setModel(modelo);
        
        for(Vehiculo i: contVeh.getVehiculos()){
            String [] actVal ={String.valueOf(i.getId_vehiculo()),i.getModelo(),i.getVariante(),String.valueOf(i.getAnio()),Double.toString(i.getPrecio_compra()),Long.toString(i.getKilometraje()),i.getTipo_gasolina(),Double.toString(i.getPrecio_venta())};
            System.out.println(actVal);
            modelo.addRow(actVal);
        }
        
    }
    private void updateTablaTenencias(){
        contVeh.ActualizarVehiculos();
        DefaultTableModel modelo = new DefaultTableModel();
        
        String [] cabecera = {"ID Vehiculo","Modelo","Tenencia"};
        
        for (String i : cabecera)
            modelo.addColumn(i);
        
        TablaTenencias.setModel(modelo);
        for(Vehiculo i: contVeh.getVehiculos()){
            String [] actVal ={String.valueOf(i.getId_vehiculo()),i.getModelo(),Boolean.toString(i.getTenencia())};
            if(!i.getTenencia())
                modelo.addRow(actVal);
        }
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar_Documentacion;
    private javax.swing.JPanel Agregar_Documentacion1;
    private javax.swing.JDialog JAgragar_Documentacion;
    private javax.swing.JDialog JConsulta_Documentacion;
    private javax.swing.JDialog JRegistroCliente;
    private javax.swing.JDialog JVentas;
    private javax.swing.JPanel PLTenencias;
    private javax.swing.JPanel PLTenencias_2;
    private javax.swing.JPanel PLVehiculos;
    private javax.swing.JPanel PLautos;
    private javax.swing.JPanel PLsalir;
    private javax.swing.JPanel PLusuario;
    private javax.swing.JTabbedPane PNVentanas;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JPanel PanelSaludo;
    private javax.swing.JPanel PanelSaludo1;
    private javax.swing.JPanel PanelSaludo2;
    private javax.swing.JPanel PanelSaludo3;
    private javax.swing.JPanel PanelSaludo4;
    public javax.swing.JTable TablaClientes1;
    public javax.swing.JTable TablaTenencias;
    public javax.swing.JTable TablaVehiculos;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnCancelarV;
    private javax.swing.JLabel btnCirculacion_C;
    private javax.swing.JLabel btnCliente_A;
    private javax.swing.JLabel btnContrato;
    private javax.swing.JLabel btnContrato_C;
    private javax.swing.JLabel btnDocumentacion;
    private javax.swing.JLabel btnDocumentacionC;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEditarCliente;
    private javax.swing.JLabel btnFactura;
    private javax.swing.JLabel btnFactura_C;
    private javax.swing.JLabel btnID;
    private javax.swing.JLabel btnIdentificacion_C;
    private javax.swing.JLabel btnMantenimiento;
    private javax.swing.JLabel btnRegistro_C;
    private javax.swing.JLabel btnTarjeta;
    private javax.swing.JLabel btnTenencia;
    private javax.swing.JLabel btnTenencia_C;
    private javax.swing.JLabel btnTenencia_P;
    private javax.swing.JLabel btnVenta;
    private javax.swing.JLabel btnVentaA;
    private javax.swing.JComboBox<String> cboDescuento;
    private TUNAME.panelCalendario cboFecha;
    private javax.swing.JComboBox<String> cboGasolina;
    private javax.swing.JComboBox<String> cboTenencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblCLN;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblNombreA;
    private javax.swing.JLabel lblNombreA2;
    private javax.swing.JLabel lblNombreA3;
    private javax.swing.JLabel lblNombreA4;
    private javax.swing.JLabel lblNombreA5;
    private javax.swing.JLabel lblNombreA6;
    private javax.swing.JLabel lblNombreA7;
    private javax.swing.JLabel lblNombreA8;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblPromedio1;
    private javax.swing.JLabel lblSaludito;
    private javax.swing.JLabel lblTextoMorado1;
    private javax.swing.JLabel lblTextoMorado2;
    private javax.swing.JLabel lblTextoMorado3;
    private javax.swing.JLabel lblTextoMorado4;
    private javax.swing.JPanel pnCrudVehiculos;
    private javax.swing.JTextField txtAmaterno;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApaterno;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCorreoE;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtVariante;
    // End of variables declaration//GEN-END:variables
}
